query CurrentOrder {
  me {
    cart {
      _id
      status
      total {
        amount
        currency
      }
      documents {
        name
        type
        size
        url
        meta
      }
      items {
        product {
          texts {
            title
            subtitle
          }
        }
      }
      meta
      billingAddress {
        firstName
        lastName
        addressLine
        postalCode
        countryCode
        city
      }
      contact {
        emailAddress
      }
      payment {
        provider {
          _id
        }
      }
      delivery {
        provider {
          _id
        }
      }
      supportedPaymentProviders {
        _id
        type
        configuration
        interface {
          label
          version
        }
      }
      supportedDeliveryProviders {
        _id
        type
        configuration
        interface {
          label
          version
        }
      }
    }
  }
}
