query CurrentPrice {
  soldItems
  product(slug: "postcard") {
    _id
    texts {
      title
      slug
    }
    ... on SimpleProduct {
      simulatedPrice {
        price {
          amount
          currency
        }
      }
      catalogPrice {
        price {
          amount
          currency
        }
      }
    }
  }
}
