query CurrentPrice {
  lastPageUrl
  postcardsSold: soldItems(slug: "postcard")
  pagesSold: soldItems(slug: "testpage")
  postcard: product(slug: "postcard") {
    _id
    texts {
      title
      slug
    }
    ... on SimpleProduct {
      simulatedPrice {
        price {
          amount
          currency
        }
      }
      catalogPrice {
        price {
          amount
          currency
        }
      }
    }
  }
  page: product(slug: "testpage") {
    _id
    texts {
      title
      slug
    }
    ... on SimpleProduct {
      simulatedPrice {
        price {
          amount
          currency
        }
      }
      catalogPrice {
        price {
          amount
          currency
        }
      }
    }
  }
}
