query CurrentPrice($postcardSlug: String!, $pageSlug: String!) {
  lastPageUrl
  postcardsSold: soldItems(slug: $postcardSlug)
  pagesSold: soldItems(slug: $pageSlug)
  postcard: product(slug: $postcardSlug) {
    _id
    texts {
      title
      slug
    }
    ... on SimpleProduct {
      simulatedPrice {
        price {
          amount
          currency
        }
      }
      catalogPrice {
        price {
          amount
          currency
        }
      }
    }
  }
  page: product(slug: $pageSlug) {
    _id
    texts {
      title
      slug
    }
    ... on SimpleProduct {
      simulatedPrice {
        price {
          amount
          currency
        }
      }
      catalogPrice {
        price {
          amount
          currency
        }
      }
    }
  }
}
