mutation SetOrderPaymentProvider($orderId: ID!, $paymentProviderId: ID!) {
  setOrderPaymentProvider(
    orderId: $orderId
    paymentProviderId: $paymentProviderId
  ) {
    _id
    payment {
      provider {
        _id
        interface {
          _id
          label
        }
      }
      ... on OrderPaymentPaypal {
        clientToken
      }
    }
  }
}
